/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package OadrSample;

import org.junit.Test;
import static org.junit.Assert.*;

public class VenSimulatorTest {
    @Test public void testSomeLibraryMethod() {
        VenSimulator classUnderTest = new VenSimulator();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.getKeyStorePath()!=null);
    }
}
